# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
#    initialization-mode: always
    data: classpath:/data.sql
    driver:
      class: com.mysql.jdbc.Driver
    url: jdbc:mysql://proxysql.master.meliseginf.com:6612/deluxedb?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect

meli:
  credential:
    db:
      host: DB_MYSQL_DESAENV03_DELUXEDB_DELUXEDB_ENDPOINT
      name: deluxedb
      username: deluxedb_RPROD
      password: DB_MYSQL_DESAENV03_DELUXEDB_DELUXEDB_RPROD

server:
  error:
    include-message: always