# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
meli:
  credential:
    db:
      host: DB_MYSQL_DESAENV03_DELUXEDB_DELUXEDB_ENDPOINT
      name: deluxedb
      username: deluxedb_RPROD
      password: DB_MYSQL_DESAENV03_DELUXEDB_DELUXEDB_RPROD
server:
  error:
    include-message: always